# Generated by Django 4.0 on 2022-01-02 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motorpool', '0002_alter_brand_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='title',
            field=models.CharField(max_length=104),
        ),
    ]
