# Generated by Django 4.0 on 2022-02-11 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motorpool', '0010_brand_slug_alter_vehiclepassport_auto'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='motorpool/brands/'),
        ),
    ]
