# Generated by Django 4.0 on 2022-03-03 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('motorpool', '0013_remove_auto_logo_favorite'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
